name: Robot Framework API Tests Empresa 1

on:
  push:
    branches:
      - main  # Executa quando houver push na branch main
  pull_request:
  workflow_dispatch:  # Habilita execução manual via botão "Run workflow"
  schedule:
    # Executa o workflow automaticamente nos horários abaixo (em UTC)
    - cron: '45 19 * * *'  # 12:33 BRT
    - cron: '50 19 * * *'  # 12:40 BRT
    - cron: '55 19 * * *'  # 12:45 BRT

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Identificar tipo de execução
        run: echo "Executado via: ${{ github.event_name }}" > execucao_info.txt

      - name: Mostrar info da execução nos logs
        run: cat execucao_info.txt

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Registrar tipo de execução do teste no relatório
        run: |
          mkdir -p results
          echo "Tipo de execução: ${{ github.event_name }}" > results/execucao_info.txt
          echo "Data e hora UTC: $(date -u)" >> results/execucao_info.txt

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot -d results tests/

      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
